Get user tests
usmqe/usmqe-testdoc pull request #11
Opened 2017-09-11 14:22 UTC by fbalak

Describe negative and positive get_user test.

2017-09-20 11:07 UTC, mkudlej requested changes

2017-09-20 11:07 UTC, mkudlej commented on api/tendrl/user_get.rst
>  user_get
Please change test name

2017-09-20 11:07 UTC, mkudlej commented on api/tendrl/user_get_negative.rst
>  user_get_negative
Please change test name

2017-09-20 11:07 UTC, mkudlej commented on api/tendrl/user_get.rst
> +#. Create user via `valid_new_user` fixture populated with user data specified
Please describe what user should be created. I think it is no good to link specific fixtures or code directly.

2017-11-01 17:23 UTC, mbukatov approved these changes

2017-11-02 12:22 UTC, mkudlej approved these changes
LGTM

2017-11-02 12:22 UTC, merged