add test case for user list
usmqe/usmqe-testdoc pull request #3
Opened 2017-09-05 08:27 UTC by mkudlej

2017-09-07 13:10 UTC, ltrilety approved these changes

2017-09-08 17:50 UTC, mbukatov requested changes
Wrong link syntax, otherwise looks good.

2017-09-08 17:50 UTC, mbukatov commented on web/tendrl/user_list.rst
> +Check user list testcase and compare it with `https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/244738633`.
Remove ` characters for the url to become a proper link.

2017-09-11 07:24 UTC, fbalak commented on web/tendrl/user_list.rst
> +#. Log out
I would use same formatting as in `Test Steps` part.

2017-09-11 07:26 UTC, fbalak approved these changes
LGTM

2017-09-12 07:48 UTC, merged