WIP: gluster_volume_profiling
usmqe/usmqe-testdoc pull request #6
Opened 2017-09-07 09:29 UTC by dahorak

2017-09-07 13:22 UTC, ltrilety requested changes
Wide volume profiling enables/disables volume profiling for all volumes existing and new ones. So the test should be made with this bearing in mind.
Moreover to check if volume profiling is enabled there has to be some volume in gluster. There should be some mention about that in test set-up.

2017-09-08 18:30 UTC, mbukatov commented on web/tendrl/gluster_volume_profiling.rst
> +(both on initial import and post import).
Could you link upstream docs for this feature?

2017-09-13 13:21 UTC, ltrilety approved these changes
LGTM

2017-11-01 16:33 UTC, mbukatov requested changes
This seems to need updates. It would be also nice to provide references to upstream docs/requirements.

2017-11-16 15:40 UTC, mbukatov commented
Clarification pending.

2017-12-07 15:43 UTC, mbukatov approved these changes
Looks good.

2017-12-07 15:43 UTC, merged