update systemd elementary checks testcase
usmqe/usmqe-testdoc pull request #8
Opened 2017-09-11 11:31 UTC by mkudlej

2017-09-13 12:17 UTC, dahorak commented on system-integration/systemd/service.tendrl_server.elementary_check.rst
> +Elementary check of tendrl-apid, tendrl-node-agent and tendrl-monitoring-integration
The name of the component and also the name of the service is ``tendrl-api`` not ``tendrl-apid``.

2017-09-13 12:17 UTC, dahorak commented on system-integration/systemd/service.tendrl_server.elementary_check.rst
> +       Check that all systemd service file is available:
If *all*, then I think it should be something like *...service files are..*.

2017-11-01 17:49 UTC, mbukatov requested changes
Oh, parametrization sucks when we don't have support for it. We could list all the items like this, but in that case, we are missing:

* tendrl-gluster-integration.service
* tendrl-notifier.service

I'm ok with just adding these 2 into this test case, even though they are not installed on the same machine ... @mkudlej Would that be ok with you?

2017-11-02 14:55 UTC, mbukatov approved these changes

2017-11-02 14:55 UTC, merged